import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconCirclePlus,
  IconCirclePlusFilled,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconShip,
  IconMail,
  IconAddressBook,
  IconFileDescription,
  IconGridDots,
  IconRobot,
  IconMessageCircle,
  IconTruck,
  IconPlane,
  IconTrain,
  IconBox,
  IconFolder,
  IconStar,
  IconStarFilled,
  IconShare
} from '@tabler/icons-react';
import {
  IconVideo,
  IconMusic,
  IconArchive,
  IconCode,
  IconDownload,
  IconExternalLink
} from '@tabler/icons-react';
import {
  IconSearch,
  IconFilter,
  IconFolderFilled,
  IconCalendar,
  IconTable,
  IconApps
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  file: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  addCircle: IconCirclePlus,
  addCircleFilled: IconCirclePlusFilled,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  ship: IconShip,
  mail: IconMail,
  addressBook: IconAddressBook,
  fileDescription: IconFileDescription,
  grid: IconGridDots,
  robot: IconRobot,
  chat: IconMessageCircle,
  road: IconTruck,
  sea: IconShip,
  air: IconPlane,
  rail: IconTrain,
  multimodal: IconGridDots,
  courier: IconBox,
  folder: IconFolder,
  folderFilled: IconFolderFilled,
  star: IconStar,
  starFilled: IconStarFilled,
  share: IconShare,
  // File type specific
  video: IconVideo,
  audio: IconMusic,
  archive: IconArchive,
  code: IconCode,
  image: IconPhoto,
  doc: IconFileText,
  // Actions
  download: IconDownload,
  external: IconExternalLink,
  filter: IconFilter,
  search: IconSearch,
  calendar: IconCalendar,
  // Extras
  sheet: IconTable,
  apps: IconApps
};
