name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run ESLint (non-blocking)
        run: |
          pnpm lint || true
      - name: Run strict lint (fail on errors) [optional]
        if: ${{ false }}
        run: pnpm lint:strict
